spring:
  application:
    name: order-service

# MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3317/order_service
    username: root
    password: Alliswell@1
#    username: maniraj
#    password: Alliswell@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

server:
  port: 8081

debug: true


inventory:
  url: http://localhost:8082