spring:
  application:
    name: product-service


# MongoDB Database Configuration
    data:
        mongodb:
        uri: mongodb://maniraj:Alliswell@1@localhost:27017/product-service?authSource=admin
#        database: product-service