spring:
  application:
    name: inventory-service

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3316/inventory_service
    username: root
    password: Alliswell@1
    #    username: maniraj
    #    password: Alliswell@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs


server:
  port: 8082

debug: true