version: '4'

services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    ports:
      - "3316:3306"
    environment:
#      MYSQL_DATABASE: inventory_service
#      MYSQL_USER: maniraj
#      MYSQL_PASSWORD: Alliswell@1
      MYSQL_ROOT_PASSWORD: Alliswell@1

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql

#    command:
#      --default-authentication-plugin=mysql_native_password

#volumes:
#  mysql-data: